#!/usr/bin/env python3
"""LITCO GAME — Expert Question Pool Generator"""
from __future__ import annotations
import json, re, uuid, random
from dataclasses import dataclass, asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GAME_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOKS = [ROOT / "leet A1.ipynb", ROOT / "leetA2.ipynb"]
OUTPUT_PATH = GAME_ROOT / "data" / "generated" / "content.json"
PUBLIC_OUTPUT_PATH = GAME_ROOT / "public" / "generated" / "content.json"

def slugify(v):
    return re.sub(r"[^a-z0-9]+", "-", v.lower()).strip("-") or "item"

def clean(v):
    v = re.sub(r"<[^>]+>", " ", v)
    v = re.sub(r"\[(.*?)\]\(.*?\)", r"\1", v)
    v = re.sub(r"[`*_#]+", "", v)
    return re.sub(r"\s+", " ", v).strip()

def extract_links(text):
    return re.findall(r"https?://[^\s\)\"']+", text)

def load_cells(nb_path):
    data = json.loads(nb_path.read_text())
    return [{"idx": i, "kind": c["cell_type"], "src": "".join(c["source"])}
            for i, c in enumerate(data["cells"])]

def detect_topic(text):
    m = re.match(r"^##\s+(.+)", text.strip())
    return clean(m.group(1)) if m else None

def detect_subtopic(text):
    m = re.match(r"^###\s+(.+)", text.strip())
    return clean(m.group(1)) if m else None

def detect_problem(text):
    links = extract_links(text)
    flat = clean(text)
    m = re.search(r"(\d+)\.\s*([A-Z][A-Za-z0-9'&/ ,\-:()+]{2,80})", flat)
    if m:
        return int(m.group(1)), m.group(2).strip().rstrip("-"), links
    m2 = re.search(r"\[(\d+)\.\s*([^\]]+)\]", text)
    if m2:
        return int(m2.group(1)), m2.group(2).strip(), links
    return None, None, links

def first_sentence(text, fallback):
    text = clean(text)
    if not text: return fallback
    return re.split(r"(?<=[.!?])\s+", text)[0][:280]

def extract_insights(text):
    kws = ["key", "idea", "approach", "intuition", "pattern", "note:", "same as",
           "difference", "must", "only diff", "careful", "edge case", "optimal", "trap", "trick"]
    res = []
    for line in text.splitlines():
        cl = clean(line)
        if 15 <= len(cl) <= 200 and any(kw in cl.lower() for kw in kws):
            res.append(cl)
    return res[:5]

def extract_cues(text, topic, subtopic):
    hay = text.lower()
    cues = []
    if "shortest path" in hay and "unweighted" in hay: cues.append("unweighted shortest path → BFS")
    if "order matters" in hay or "permutation" in hay: cues.append("order matters → permutations → target outer loop")
    if "monotonic" in hay or "next greater" in hay: cues.append("nearest greater/smaller → monotonic stack")
    if "prefix" in hay and "sum" in hay: cues.append("subarray sum query → prefix sum")
    if "sliding window" in hay or "at most k" in hay: cues.append("contiguous subarray with constraint → sliding window")
    if "binary search" in hay or "sorted" in hay: cues.append("sorted/rotated array or answer range → binary search")
    if "topo" in hay or "prerequisite" in hay: cues.append("dependency ordering → topological sort")
    if "knapsack" in hay or "0/1" in hay: cues.append("item selection with capacity → knapsack DP")
    if not cues: cues.append(f"{topic} pattern")
    return cues[:4]

def parse_notebooks(paths):
    topics_map = {}
    problems = []

    for nb_path in paths:
        nb_name = nb_path.name
        cells = load_cells(nb_path)
        cur_topic = "General"; cur_topic_id = "general"
        cur_subtopic = "General"; cur_subtopic_id = "general"
        difficulty = "medium"
        prob_title = None; prob_number = None; prob_links = []
        prob_md = []; prob_code = []; prob_cells_idx = []

        def flush():
            nonlocal prob_title, prob_number, prob_links, prob_md, prob_code, prob_cells_idx
            if not prob_title: return
            all_md = "\n".join(prob_md); all_code = "\n".join(prob_code)
            summary = first_sentence(all_md, prob_title)
            insights = extract_insights(all_md + "\n" + all_code)
            cues = extract_cues(all_md, cur_topic, cur_subtopic)
            pid = f"lc-{prob_number}-{slugify(prob_title)}" if prob_number else f"lc-{slugify(prob_title)}"
            if not any(p["id"] == pid for p in problems):
                problems.append({"id": pid, "title": prob_title, "number": prob_number,
                    "topic": cur_topic, "subtopic": cur_subtopic,
                    "topicId": cur_topic_id, "subtopicId": cur_subtopic_id,
                    "difficulty": difficulty, "notebook": nb_name,
                    "source_cells": list(prob_cells_idx),
                    "summary": summary, "notes": all_md[:1200],
                    "code": all_code[:3000], "links": list(set(prob_links)),
                    "insights": insights[:5], "recognition_cues": cues[:4]})
            prob_title = None; prob_number = None; prob_links = []
            prob_md = []; prob_code = []; prob_cells_idx = []

        for cell in cells:
            text = cell["src"]; kind = cell["kind"]; idx = cell["idx"]
            t = detect_topic(text)
            if t and kind == "markdown":
                flush(); cur_topic = t; cur_topic_id = slugify(t)
                cur_subtopic = t; cur_subtopic_id = slugify(t)
                if cur_topic_id not in topics_map:
                    topics_map[cur_topic_id] = {"id": cur_topic_id, "title": cur_topic, "subtopics": set()}
                continue
            st = detect_subtopic(text)
            if st and kind == "markdown":
                flush(); cur_subtopic = st; cur_subtopic_id = slugify(st)
                if cur_topic_id in topics_map: topics_map[cur_topic_id]["subtopics"].add(cur_subtopic)
                continue
            if kind == "markdown" and text.strip().startswith("####"):
                num, title, links = detect_problem(text)
                if title and len(title) > 3:
                    flush(); prob_title = title; prob_number = num; prob_links = links
                    prob_cells_idx = [idx]; prob_md = [text]
                    difficulty = "hard" if "hard" in text.lower() else "easy" if "easy" in text.lower() else "medium"
                    continue
            if prob_title:
                prob_cells_idx.append(idx)
                if kind == "markdown": prob_md.append(text); prob_links.extend(extract_links(text))
                else: prob_code.append(text)
            elif kind == "code":
                m = re.match(r"#\s*(\d+)\.\s*(.+)", text.strip())
                if m:
                    flush(); prob_number = int(m.group(1))
                    prob_title = m.group(2).strip().split("\n")[0][:80]
                    prob_cells_idx = [idx]; prob_code = [text]
        flush()

    topics = [{"id": t["id"], "title": t["title"], "subtopics": sorted(t["subtopics"])}
              for t in topics_map.values()]
    topics.sort(key=lambda x: x["title"])
    return topics, problems


HANDCRAFTED = [
    {"id":"hq-ah-two-sum","problemId":"lc-1-two-sum","topic":"Arrays & Hashing","topicId":"arrays-hashing","subtopic":"Frequency Map","subtopicId":"frequency-map","difficulty":"easy","title":"Two Sum — O(n)","questionType":"multiple_choice","prompt":"Two Sum (LC 1): Given nums and target, return indices of two numbers that sum to target. Which achieves O(n)?","answer":"HashMap storing num→index; check if (target - num) is in map at each step","acceptedAnswers":["hashmap","num→index","use a hashmap"],"choices":["HashMap storing num→index; check if (target - num) is in map at each step","Sort array, use two pointers from each end","Binary search for each complement","Nested loop checking every pair"],"tags":["hashmap","recognition"],"timeLimitSec":15,"masteryWeight":1.0,"fullCode":"def twoSum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen:\n            return [seen[target - n], i]\n        seen[n] = i","fullExplanation":"Use hashmap for O(1) complement lookup. Store num→index. At each element check if (target - current) exists. Sorting+two-pointers works but loses original indices.","links":["https://leetcode.com/problems/two-sum/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-bs-rotated-min","problemId":"lc-153-find-min-rotated","topic":"Binary Search","topicId":"binary-search","subtopic":"Rotated Array","subtopicId":"rotated-array","difficulty":"medium","title":"Find Min in Rotated — decision","questionType":"multiple_choice","prompt":"Find Minimum in Rotated Sorted Array (LC 153): When nums[mid] > nums[right], where is the minimum?","answer":"RIGHT half — set left = mid + 1","acceptedAnswers":["right half","left = mid + 1"],"choices":["RIGHT half — set left = mid + 1","LEFT half — set right = mid - 1","At nums[mid] — return immediately","Cannot determine — check both halves"],"tags":["binary-search","rotated"],"timeLimitSec":20,"masteryWeight":1.3,"fullCode":"def findMin(nums):\n    l, r = 0, len(nums) - 1\n    while l < r:\n        mid = (l + r) // 2\n        if nums[mid] > nums[r]: l = mid + 1  # min on RIGHT\n        else: r = mid\n    return nums[l]","fullExplanation":"If nums[mid] > nums[right], the rotation jump is in the right portion → minimum is in the RIGHT half. If nums[mid] <= nums[right], minimum is at mid or left. Always compare against nums[right].","links":["https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-bs-left-bound","problemId":"","topic":"Binary Search","topicId":"binary-search","subtopic":"Left Bound","subtopicId":"left-bound","difficulty":"medium","title":"Binary Search left bound","questionType":"fill_blank","prompt":"Binary search LEFT bound (first occurrence): when nums[mid] == target, set r = ___ (not mid-1).","answer":"r = mid","acceptedAnswers":["r = mid","right = mid","hi = mid"],"choices":[],"tags":["binary-search","boundary"],"timeLimitSec":12,"masteryWeight":1.0,"fullCode":"def left_bound(nums, target):\n    l, r = 0, len(nums) - 1\n    while l < r:\n        mid = (l + r) // 2\n        if nums[mid] < target: l = mid + 1\n        else: r = mid  # keep mid\n    return l if nums[l] == target else -1","fullExplanation":"Left bound: r=mid keeps mid in range when match found. Right bound: l=mid; use upper mid=(l+r+1)//2 to avoid infinite loop.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-sw-non-neg","problemId":"","topic":"Sliding Window","topicId":"sliding-window","subtopic":"Variable Size","subtopicId":"variable-size","difficulty":"medium","title":"Sliding Window — non-negative rule","questionType":"multiple_choice","prompt":"A shrinkable sliding window only works correctly when all values are ___. Why?","answer":"Non-negative — adding always increases sum, shrinking always decreases (monotone property needed)","acceptedAnswers":["non-negative","positive or zero"],"choices":["Non-negative — adding always increases sum, shrinking always decreases (monotone property needed)","Positive integers only — zeros cause stall","Any integers — window auto-adjusts","Sorted — sliding window requires sorted input"],"tags":["sliding-window","pitfall"],"timeLimitSec":20,"masteryWeight":1.3,"fullCode":"def maxLen(nums, k):\n    l = total = res = 0\n    for r in range(len(nums)):\n        total += nums[r]\n        while total > k: total -= nums[l]; l += 1\n        res = max(res, r - l + 1)\n    return res","fullExplanation":"With negatives: removing from left might INCREASE sum — breaks shrinking logic. The window assumes monotone relationship. With negatives → prefix sum + hashmap instead.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-sw-vs-prefix","problemId":"lc-560-subarray-sum-k","topic":"Sliding Window","topicId":"sliding-window","subtopic":"Contrast","subtopicId":"contrast","difficulty":"medium","title":"Subarray Sum = k — SW vs Prefix","questionType":"this_or_that","prompt":"Subarray Sum Equals K (LC 560): array has NEGATIVE integers, find subarrays with sum = k. Sliding window or prefix sum?","answer":"Prefix Sum + Hashmap — sliding window fails with negatives. prefix[j]-prefix[i]=k → count (prefix-k) seen before.","acceptedAnswers":["prefix sum","prefix sum + hashmap"],"choices":["Prefix Sum + Hashmap — sliding window fails with negatives. prefix[j]-prefix[i]=k → count (prefix-k) seen before.","Sliding Window — works for all values","Both equivalent — choose by preference","Binary search on cumulative sum"],"tags":["contrast","prefix-sum","sliding-window"],"timeLimitSec":20,"masteryWeight":1.4,"fullCode":"from collections import defaultdict\ndef subarraySum(nums, k):\n    prefix_count = defaultdict(int)\n    prefix_count[0] = 1\n    prefix = res = 0\n    for n in nums:\n        prefix += n\n        res += prefix_count[prefix - k]\n        prefix_count[prefix] += 1\n    return res","fullExplanation":"KEY: sliding window needs non-negative. Negatives → prefix sum + hashmap. If prefix[j]-prefix[i]=k, subarray [i+1..j] sums to k. Store prefix_count[prefix] = times seen.","links":["https://leetcode.com/problems/subarray-sum-equals-k/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-ms-direction","problemId":"","topic":"Stack / Monotonic Stack","topicId":"stack-monotonic-stack","subtopic":"Monotonic Stack","subtopicId":"monotonic-stack","difficulty":"medium","title":"Monotonic Stack direction","questionType":"multiple_choice","prompt":"To find NEXT GREATER element: maintain ___ stack. To find NEXT SMALLER: maintain ___ stack.","answer":"Decreasing for next greater; Increasing for next smaller","acceptedAnswers":["decreasing for next greater","decreasing stack"],"choices":["Decreasing for next greater; Increasing for next smaller","Increasing for next greater; Decreasing for next smaller","Both use decreasing; comparison operator changes","Direction doesn't matter — pop condition controls it"],"tags":["monotonic-stack","direction"],"timeLimitSec":20,"masteryWeight":1.3,"fullCode":"def nextGreater(nums):\n    res = [-1]*len(nums); stack = []\n    for i, n in enumerate(nums):\n        while stack and nums[stack[-1]] < n:\n            res[stack.pop()] = n\n        stack.append(i)\n    return res","fullExplanation":"DECREASING stack: pop when current is GREATER → gives NEXT GREATER. INCREASING stack: pop when current is SMALLER → gives NEXT SMALLER. Always store INDICES.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-ps-balance","problemId":"lc-525-contiguous-array","topic":"Prefix Sum","topicId":"prefix-sum","subtopic":"Balance Key","subtopicId":"balance-key","difficulty":"medium","title":"Contiguous Array — 0→-1 trick","questionType":"multiple_choice","prompt":"Contiguous Array (LC 525): Longest subarray with equal 0s and 1s. What transformation enables prefix sum?","answer":"Replace 0 with -1; find longest subarray sum=0 using prefix balance hashmap","acceptedAnswers":["replace 0 with -1","0→-1","map 0 to -1"],"choices":["Replace 0 with -1; find longest subarray sum=0 using prefix balance hashmap","Track (count_0, count_1) tuples as key","Binary search on subarray length","Sort to group 0s and 1s, then two pointers"],"tags":["prefix-sum","balance","transformation"],"timeLimitSec":20,"masteryWeight":1.3,"fullCode":"def findMaxLength(nums):\n    prefix_index = {0: -1}\n    balance = res = 0\n    for i, n in enumerate(nums):\n        balance += 1 if n==1 else -1\n        if balance in prefix_index: res = max(res, i - prefix_index[balance])\n        else: prefix_index[balance] = i  # earliest index\n    return res","fullExplanation":"Transform 0→-1. Equal 0s and 1s → sum=0. Same balance at i and j → subarray [i+1..j] sums to 0. Store EARLIEST index for each balance. Only store if balance not in map.","links":["https://leetcode.com/problems/contiguous-array/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-tr-diameter","problemId":"lc-543-diameter","topic":"Trees","topicId":"trees","subtopic":"Path Problems","subtopicId":"path-problems","difficulty":"easy","title":"Tree Diameter — return vs track","questionType":"multiple_choice","prompt":"Diameter of Binary Tree (LC 543): at each node, what do you RETURN to parent vs what do you TRACK globally?","answer":"Return 1+max(l,r) (height); Track max(l+r) globally (diameter through this node)","acceptedAnswers":["return height track diameter","1+max(l,r)","return height"],"choices":["Return 1+max(l,r) (height); Track max(l+r) globally (diameter through this node)","Return l+r (diameter); Track 1+max(l,r) globally","Return max(l,r); Track l+r+1","Return and track same value — equals height"],"tags":["trees","dfs","diameter"],"timeLimitSec":18,"masteryWeight":1.2,"fullCode":"def diameterOfBinaryTree(root):\n    res = [0]\n    def depth(node):\n        if not node: return 0\n        l = depth(node.left); r = depth(node.right)\n        res[0] = max(res[0], l + r)\n        return 1 + max(l, r)\n    depth(root); return res[0]","fullExplanation":"Separate RETURN (height=1+max(l,r)) from TRACK (diameter=l+r). Common trap: returning l+r breaks height computation for parent.","links":["https://leetcode.com/problems/diameter-of-binary-tree/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-tr-level-order","problemId":"lc-102-level-order","topic":"Trees","topicId":"trees","subtopic":"BFS Level Order","subtopicId":"bfs-level-order","difficulty":"medium","title":"Level Order BFS template","questionType":"multiple_choice","prompt":"Binary Tree Level Order (LC 102): the key that processes exactly ONE level per iteration is ___","answer":"Snapshot len(queue) at start of while loop: for _ in range(len(queue)) = exactly this level","acceptedAnswers":["snapshot queue length","range(len(queue))"],"choices":["Snapshot len(queue) at start of while loop: for _ in range(len(queue)) = exactly this level","None sentinel between levels","DFS with depth parameter","Pop until empty — one pop = one level"],"tags":["trees","bfs","level-order"],"timeLimitSec":15,"masteryWeight":1.1,"fullCode":"from collections import deque\ndef levelOrder(root):\n    if not root: return []\n    queue = deque([root]); res = []\n    while queue:\n        level = []\n        for _ in range(len(queue)):  # snapshot = this level\n            node = queue.popleft(); level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        res.append(level)\n    return res","fullExplanation":"Template: snapshot len(queue) = nodes in current level. Process that many nodes. Their children = next level. Canonical BFS level-order pattern.","links":["https://leetcode.com/problems/binary-tree-level-order-traversal/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-bt-combo-vs-perm","problemId":"","topic":"Backtracking","topicId":"backtracking","subtopic":"Combinations vs Permutations","subtopicId":"contrast","difficulty":"medium","title":"Combinations vs Permutations","questionType":"multiple_choice","prompt":"Backtracking — key structural difference between combinations and permutations:","answer":"Combinations: loop from 'start'; Permutations: loop from 0 with visited set","acceptedAnswers":["loop from start vs 0","combinations from start"],"choices":["Combinations: loop from 'start'; Permutations: loop from 0 with visited set","Both loop from 0; difference is duplicate handling","Combinations use BFS; Permutations use DFS","Permutations loop from start; Combinations loop from 0"],"tags":["backtracking","contrast"],"timeLimitSec":20,"masteryWeight":1.4,"fullCode":"def combine(n,k):\n    res=[]\n    def bt(start, path):\n        if len(path)==k: res.append(path[:]); return\n        for i in range(start,n+1): bt(i+1, path+[i])\n    bt(1,[]); return res\n\ndef permute(nums):\n    res=[]\n    def bt(path, used):\n        if len(path)==len(nums): res.append(path[:]); return\n        for i in range(len(nums)):\n            if not used[i]: used[i]=True; bt(path+[nums[i]],used); used[i]=False\n    bt([],[False]*len(nums)); return res","fullExplanation":"COMBINATIONS: pass start → each element used once, no order duplicates. PERMUTATIONS: always loop from 0 + visited set → every element at every position.","links":["https://leetcode.com/problems/combinations/","https://leetcode.com/problems/permutations/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-bt-subsets","problemId":"","topic":"Backtracking","topicId":"backtracking","subtopic":"Subsets","subtopicId":"subsets","difficulty":"medium","title":"Subsets vs Combination Sum — when to record","questionType":"multiple_choice","prompt":"Subsets (LC 78) vs Combination Sum (LC 39): when do you add to results?","answer":"Subsets: record at EVERY recursive call; Combination Sum: record only when remain==0","acceptedAnswers":["record every call vs remain 0","subsets always record"],"choices":["Subsets: record at EVERY recursive call; Combination Sum: record only when remain==0","Both record only at leaf nodes","Combination Sum records every call; Subsets only at target size","Both identical except duplicate handling"],"tags":["backtracking","subsets","contrast"],"timeLimitSec":18,"masteryWeight":1.2,"fullCode":"def subsets(nums):\n    res=[]\n    def bt(start,path):\n        res.append(path[:])  # always record\n        for i in range(start,len(nums)): bt(i+1,path+[nums[i]])\n    bt(0,[]); return res\n\ndef combinationSum(c,target):\n    res=[]\n    def bt(start,remain,path):\n        if remain==0: res.append(path[:]); return\n        if remain<0: return\n        for i in range(start,len(c)): bt(i,remain-c[i],path+[c[i]])\n    bt(0,target,[]); return res","fullExplanation":"Subsets: add every intermediate path. CombSum: add only when remain==0. CombSum allows reuse (bt(i,...) not bt(i+1,...)).","links":["https://leetcode.com/problems/subsets/","https://leetcode.com/problems/combination-sum/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-hp-kth","problemId":"lc-215-kth-largest","topic":"Heap / Priority Queue","topicId":"heap-priority-queue","subtopic":"K-th Element","subtopicId":"kth-element","difficulty":"medium","title":"Kth Largest — min-heap of k","questionType":"multiple_choice","prompt":"Kth Largest Element (LC 215): which heap approach gives O(n log k)?","answer":"MIN-heap of size k: push each element, pop when size>k; root=kth largest","acceptedAnswers":["min-heap of size k","min heap k"],"choices":["MIN-heap of size k: push each element, pop when size>k; root=kth largest","MAX-heap of size k: root is always kth largest","Push all into MAX-heap, pop k times","MIN-heap of size n-k; root is the answer"],"tags":["heap","kth","counter-intuitive"],"timeLimitSec":18,"masteryWeight":1.2,"fullCode":"import heapq\ndef findKthLargest(nums,k):\n    h=[]\n    for n in nums:\n        heapq.heappush(h,n)\n        if len(h)>k: heapq.heappop(h)\n    return h[0]","fullExplanation":"Counter-intuitive: MIN-heap of size k for Kth LARGEST. Heap keeps top k largest; root (minimum of those k) = kth largest. When >k, pop minimum.","links":["https://leetcode.com/problems/kth-largest-element-in-an-array/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-bfs-unweighted","problemId":"","topic":"Graphs","topicId":"graphs","subtopic":"BFS vs DFS","subtopicId":"bfs-vs-dfs","difficulty":"easy","title":"BFS vs DFS — shortest path","questionType":"this_or_that","prompt":"Shortest path in UNWEIGHTED graph: BFS or DFS?","answer":"BFS — level-by-level; first time you reach destination = shortest path. DFS may find longer path first.","acceptedAnswers":["BFS","bfs"],"choices":["BFS — level-by-level; first time you reach destination = shortest path. DFS may find longer path first.","DFS — goes deep faster","Both produce same result","Dijkstra — always required for shortest path"],"tags":["graphs","bfs","shortest-path"],"timeLimitSec":12,"masteryWeight":1.0,"fullCode":"from collections import deque\ndef shortestPath(graph,src,dst):\n    q=deque([(src,0)]); vis={src}\n    while q:\n        node,d=q.popleft()\n        if node==dst: return d\n        for nei in graph[node]:\n            if nei not in vis: vis.add(nei); q.append((nei,d+1))\n    return -1","fullExplanation":"BFS for shortest path in unweighted graph. First arrival = min hops. Dijkstra for weighted. DFS finds A path, not necessarily shortest.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-dijkstra","problemId":"","topic":"Graphs","topicId":"graphs","subtopic":"Shortest Path Algorithms","subtopicId":"shortest-path","difficulty":"medium","title":"BFS vs Dijkstra — when","questionType":"multiple_choice","prompt":"When do you use Dijkstra instead of BFS?","answer":"When edge weights are non-uniform — BFS requires equal edge weights","acceptedAnswers":["non-uniform weights","weighted edges"],"choices":["When edge weights are non-uniform — BFS requires equal edge weights","When graph has cycles","When graph is directed","When graph has more than 1000 nodes"],"tags":["graphs","dijkstra","contrast"],"timeLimitSec":18,"masteryWeight":1.3,"fullCode":"import heapq\ndef dijkstra(graph,src,n):\n    dist=[float('inf')]*n; dist[src]=0\n    heap=[(0,src)]\n    while heap:\n        cost,u=heapq.heappop(heap)\n        if cost>dist[u]: continue\n        for v,w in graph[u]:\n            if dist[u]+w<dist[v]:\n                dist[v]=dist[u]+w; heapq.heappush(heap,(dist[v],v))\n    return dist","fullExplanation":"BFS: unit-weight graphs. Dijkstra: non-negative weighted. Bellman-Ford: negative edges. Dijkstra uses min-heap to always expand cheapest node.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-pacific","problemId":"lc-417-pacific-atlantic","topic":"Graphs","topicId":"graphs","subtopic":"Matrix as Graph","subtopicId":"matrix-as-graph","difficulty":"medium","title":"Pacific Atlantic — reverse DFS","questionType":"multiple_choice","prompt":"Pacific Atlantic (LC 417): Why DFS from ocean BORDERS inward instead of from each cell outward?","answer":"O(mn) vs O(m²n²) — reverse DFS from borders visits each cell at most twice total","acceptedAnswers":["O(mn)","reverse reduces complexity","each cell once"],"choices":["O(mn) vs O(m²n²) — reverse DFS from borders visits each cell at most twice total","Simpler implementation","Border cells drain to both oceans","Oceans have no height — avoids edge cases"],"tags":["graphs","matrix","reverse-thinking"],"timeLimitSec":25,"masteryWeight":1.4,"fullCode":"def pacificAtlantic(heights):\n    m,n=len(heights),len(heights[0])\n    pac,atl=set(),set()\n    def dfs(r,c,vis):\n        vis.add((r,c))\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n            nr,nc=r+dr,c+dc\n            if 0<=nr<m and 0<=nc<n and (nr,nc) not in vis:\n                if heights[nr][nc]>=heights[r][c]: dfs(nr,nc,vis)\n    for r in range(m): dfs(r,0,pac); dfs(r,n-1,atl)\n    for c in range(n): dfs(0,c,pac); dfs(m-1,c,atl)\n    return [[r,c] for r in range(m) for c in range(n) if (r,c) in pac and (r,c) in atl]","fullExplanation":"Reverse: start from ocean borders and go UPHILL (neighbor height >= current). Each ocean does one DFS pass. Intersection = answer. Forward (each cell downhill) = O(m²n²).","links":["https://leetcode.com/problems/pacific-atlantic-water-flow/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-topo","problemId":"lc-210-course-schedule","topic":"Graphs","topicId":"graphs","subtopic":"Topological Sort","subtopicId":"topological-sort","difficulty":"medium","title":"Kahn's Topo — init queue","questionType":"multiple_choice","prompt":"Kahn's BFS topological sort (LC 210): initialize BFS queue with ___","answer":"All nodes with in-degree = 0 (no prerequisites)","acceptedAnswers":["in-degree 0","zero in-degree"],"choices":["All nodes with in-degree = 0 (no prerequisites)","Node 0 only","All nodes — filter as you process","Nodes with highest out-degree"],"tags":["topological-sort","kahn","in-degree"],"timeLimitSec":15,"masteryWeight":1.2,"fullCode":"from collections import deque,defaultdict\ndef findOrder(n,prereqs):\n    g=defaultdict(list); ind=[0]*n\n    for a,b in prereqs: g[b].append(a); ind[a]+=1\n    q=deque([i for i in range(n) if ind[i]==0]); order=[]\n    while q:\n        node=q.popleft(); order.append(node)\n        for nei in g[node]:\n            ind[nei]-=1\n            if ind[nei]==0: q.append(nei)\n    return order if len(order)==n else []","fullExplanation":"Kahn's: 1) Build graph + in-degree. 2) Queue all in-degree-0 nodes. 3) Pop→order→decrement neighbors→enqueue if in-degree hits 0. 4) len(order)!=n → cycle.","links":["https://leetcode.com/problems/course-schedule-ii/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-union-find","problemId":"","topic":"Graphs","topicId":"graphs","subtopic":"Union Find","subtopicId":"union-find","difficulty":"medium","title":"Union Find — path compression","questionType":"fill_blank","prompt":"Union Find path compression: in find(x), set parent[x] = ___ to flatten tree.","answer":"find(parent[x])","acceptedAnswers":["find(parent[x])","root","recursive path compression"],"choices":[],"tags":["union-find","path-compression"],"timeLimitSec":15,"masteryWeight":1.0,"fullCode":"class UF:\n    def __init__(self,n): self.p=list(range(n)); self.r=[0]*n\n    def find(self,x):\n        if self.p[x]!=x: self.p[x]=self.find(self.p[x])  # path compression\n        return self.p[x]\n    def union(self,x,y):\n        rx,ry=self.find(x),self.find(y)\n        if rx==ry: return False\n        if self.r[rx]<self.r[ry]: rx,ry=ry,rx\n        self.p[ry]=rx\n        if self.r[rx]==self.r[ry]: self.r[rx]+=1\n        return True","fullExplanation":"Path compression: during find(), set parent[x]=root for every node on the path. Future finds are O(1). With union by rank → near O(α(n)) amortized.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-dp-knapsack-dir","problemId":"","topic":"Dynamic Programming","topicId":"dynamic-programming","subtopic":"Knapsack DP","subtopicId":"knapsack-dp","difficulty":"medium","title":"0/1 Knapsack — loop direction","questionType":"multiple_choice","prompt":"Optimized 1D 0/1 Knapsack: iterate capacity from ___ to ___. Why?","answer":"RIGHT TO LEFT (high→0): prevents item being used twice in same pass","acceptedAnswers":["right to left","high to low","capacity down to 0"],"choices":["RIGHT TO LEFT (high→0): prevents item being used twice in same pass","LEFT TO RIGHT — ensures all capacities considered","Either direction — same result","LEFT TO RIGHT for 0/1, RIGHT TO LEFT for unbounded (opposite of truth)"],"tags":["dp","knapsack","loop-direction"],"timeLimitSec":20,"masteryWeight":1.5,"fullCode":"def knapsack01(weights,values,cap):\n    dp=[0]*(cap+1)\n    for i in range(len(weights)):\n        for w in range(cap,weights[i]-1,-1):  # RIGHT TO LEFT\n            dp[w]=max(dp[w],dp[w-weights[i]]+values[i])\n    return dp[cap]\n\ndef unbounded(weights,values,cap):\n    dp=[0]*(cap+1)\n    for i in range(len(weights)):\n        for w in range(weights[i],cap+1):  # LEFT TO RIGHT = allow reuse\n            dp[w]=max(dp[w],dp[w-weights[i]]+values[i])\n    return dp[cap]","fullExplanation":"0/1 → RIGHT TO LEFT: dp[w-weight] = previous item's row (not yet updated this pass). L→R: dp[w-weight] already includes item i → item used twice = unbounded. UNBOUNDED → intentionally L→R to allow reuse.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-dp-coin-vs-comb4","problemId":"","topic":"Dynamic Programming","topicId":"dynamic-programming","subtopic":"Knapsack DP","subtopicId":"knapsack-dp","difficulty":"hard","title":"Coin Change II vs Combination Sum IV","questionType":"multiple_choice","prompt":"Coin Change II (LC 518) counts combinations. Combination Sum IV (LC 377) counts permutations. Which has COINS as outer loop?","answer":"Coin Change II — coins outer prevents duplicate combos; Comb Sum IV has TARGET as outer loop","acceptedAnswers":["Coin Change II","CC2 outer coins","coin change coins outer"],"choices":["Coin Change II — coins outer prevents duplicate combos; Comb Sum IV has TARGET as outer loop","Combination Sum IV — coins outer","Both have coins outer","Neither — both use target outer but different base cases"],"tags":["dp","knapsack","permutations","contrast"],"timeLimitSec":25,"masteryWeight":1.6,"fullCode":"def change(amount,coins):\n    dp=[0]*(amount+1); dp[0]=1\n    for coin in coins:          # COINS outer = combinations\n        for w in range(coin,amount+1): dp[w]+=dp[w-coin]\n    return dp[amount]\n\ndef combinationSum4(nums,target):\n    dp=[0]*(target+1); dp[0]=1\n    for w in range(1,target+1):  # TARGET outer = permutations\n        for num in nums:\n            if w>=num: dp[w]+=dp[w-num]\n    return dp[target]","fullExplanation":"COMBINATIONS = COINS outer: each denomination once per pass → [1,2] and [2,1] same combo. PERMUTATIONS = TARGET outer: try all coins for each amount → different orders counted. Mnemonic: ORDER MATTERS → TARGET outer.","links":["https://leetcode.com/problems/coin-change-ii/","https://leetcode.com/problems/combination-sum-iv/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-dp-lcs","problemId":"","topic":"Dynamic Programming","topicId":"dynamic-programming","subtopic":"Dual-Sequence DP","subtopicId":"dual-sequence","difficulty":"medium","title":"LCS — mismatch formula","questionType":"fill_blank","prompt":"LCS (LC 1143): dp[i][j] = dp[i-1][j-1]+1 if match, else ___.","answer":"max(dp[i-1][j], dp[i][j-1])","acceptedAnswers":["max(dp[i-1][j], dp[i][j-1])","max skip either"],"choices":[],"tags":["dp","lcs","transition"],"timeLimitSec":15,"masteryWeight":1.2,"fullCode":"def longestCommonSubsequence(s1,s2):\n    m,n=len(s1),len(s2)\n    dp=[[0]*(n+1) for _ in range(m+1)]\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if s1[i-1]==s2[j-1]: dp[i][j]=dp[i-1][j-1]+1\n            else: dp[i][j]=max(dp[i-1][j],dp[i][j-1])\n    return dp[m][n]","fullExplanation":"LCS mismatch: max(skip s1 char, skip s2 char). Edit Distance mismatch: 1+min(delete,insert,replace). Know both transitions.","links":["https://leetcode.com/problems/longest-common-subsequence/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-dp-edit","problemId":"","topic":"Dynamic Programming","topicId":"dynamic-programming","subtopic":"Dual-Sequence DP","subtopicId":"dual-sequence","difficulty":"medium","title":"Edit Distance — mismatch","questionType":"multiple_choice","prompt":"Edit Distance (LC 72): when s1[i]!=s2[j], dp[i][j] = 1 + min(___)?","answer":"1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])  — delete, insert, replace","acceptedAnswers":["min of three","dp[i-1][j] dp[i][j-1] dp[i-1][j-1]"],"choices":["1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])  — delete, insert, replace","1 + max(dp[i-1][j], dp[i][j-1])","dp[i-1][j-1] + 2","max(dp[i-1][j], dp[i][j-1]) — same as LCS"],"tags":["dp","edit-distance","transition"],"timeLimitSec":20,"masteryWeight":1.3,"fullCode":"def minDistance(s1,s2):\n    m,n=len(s1),len(s2)\n    dp=[[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0]=i\n    for j in range(n+1): dp[0][j]=j\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if s1[i-1]==s2[j-1]: dp[i][j]=dp[i-1][j-1]\n            else: dp[i][j]=1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])","fullExplanation":"3 ops: dp[i-1][j]=delete s1[i], dp[i][j-1]=insert s2[j], dp[i-1][j-1]=replace. Contrast with LCS mismatch=max.","links":["https://leetcode.com/problems/edit-distance/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-dp-lis","problemId":"","topic":"Dynamic Programming","topicId":"dynamic-programming","subtopic":"Non-constant Transition DP","subtopicId":"non-constant","difficulty":"hard","title":"LIS — O(n²) vs O(n log n)","questionType":"multiple_choice","prompt":"LIS (LC 300): what can O(n²) DP do that O(n log n) tails CANNOT easily?","answer":"Reconstruct the actual LIS — tails overwrites values, making path reconstruction hard","acceptedAnswers":["reconstruct subsequence","path reconstruction"],"choices":["Reconstruct the actual LIS — tails overwrites values, making path reconstruction hard","Handle duplicate values","Work on 2D input","Run faster — better constants"],"tags":["dp","lis","tradeoff","contrast"],"timeLimitSec":25,"masteryWeight":1.4,"fullCode":"def lisDP(nums):\n    dp=[1]*len(nums)\n    for i in range(len(nums)):\n        for j in range(i):\n            if nums[j]<nums[i]: dp[i]=max(dp[i],dp[j]+1)\n    return max(dp)\n\nimport bisect\ndef lisBin(nums):\n    tails=[]\n    for n in nums:\n        pos=bisect.bisect_left(tails,n)\n        if pos==len(tails): tails.append(n)\n        else: tails[pos]=n  # NOT actual LIS\n    return len(tails)","fullExplanation":"O(n²) DP: dp[i]=LIS ending at i → backtrack for reconstruction. O(n log n) tails: smallest tail for each length → binary search. Tails not actual LIS. For reconstruction: DP. For length only: tails.","links":["https://leetcode.com/problems/longest-increasing-subsequence/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-interval-sched","problemId":"lc-435-non-overlap","topic":"Greedy","topicId":"greedy","subtopic":"Interval Scheduling","subtopicId":"interval-scheduling","difficulty":"medium","title":"Non-overlapping Intervals — sort key","questionType":"multiple_choice","prompt":"Non-overlapping Intervals (LC 435): to minimize removals, sort by ___.","answer":"END TIME — earliest-deadline-first maximizes intervals kept","acceptedAnswers":["end time","sort by end"],"choices":["END TIME — earliest-deadline-first maximizes intervals kept","Start time — chronological order","Length (shortest first)","Start time descending"],"tags":["greedy","intervals","sort-key"],"timeLimitSec":18,"masteryWeight":1.2,"fullCode":"def eraseOverlapIntervals(intervals):\n    intervals.sort(key=lambda x:x[1])  # END TIME\n    count=0; prev_end=float('-inf')\n    for start,end in intervals:\n        if start>=prev_end: prev_end=end\n        else: count+=1\n    return count","fullExplanation":"Earliest deadline first: sort by end time. Keep intervals that don't overlap with last kept. Overlapping ones are removed. Minimizes removals.","links":["https://leetcode.com/problems/non-overlapping-intervals/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-ll-cycle","problemId":"lc-141-cycle","topic":"Linked List","topicId":"linked-list","subtopic":"Fast/Slow Pointers","subtopicId":"fast-slow-pointers","difficulty":"easy","title":"Cycle Detection — why they meet","questionType":"multiple_choice","prompt":"Floyd's cycle: once inside cycle, why do fast (2x) and slow (1x) always meet?","answer":"Fast gains 1 step per iteration in cycle; gap decreases by 1 each step until 0","acceptedAnswers":["gap decreases by 1","fast gains 1 step"],"choices":["Fast gains 1 step per iteration in cycle; gap decreases by 1 each step until 0","Fast laps slow after cycle_length steps","They meet at cycle entry point exactly","Slow waits; fast loops until returns"],"tags":["linked-list","cycle","proof"],"timeLimitSec":18,"masteryWeight":1.1,"fullCode":"def hasCycle(head):\n    slow=fast=head\n    while fast and fast.next:\n        slow=slow.next; fast=fast.next.next\n        if slow==fast: return True\n    return False","fullExplanation":"Inside cycle: relative speed of fast = +1/iteration. Gap G → after G steps gap=0 → they meet. For cycle start (LC 142): reset one to head, advance both 1 step → meet at cycle start.","links":["https://leetcode.com/problems/linked-list-cycle/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-ll-reverse","problemId":"lc-206-reverse","topic":"Linked List","topicId":"linked-list","subtopic":"Reversal","subtopicId":"reversal","difficulty":"easy","title":"Reverse Linked List — order","questionType":"multiple_choice","prompt":"Reverse Linked List (LC 206) iterative: correct order of pointer updates?","answer":"1. nxt=cur.next  2. cur.next=prev  3. prev=cur  4. cur=nxt","acceptedAnswers":["save next first","nxt cur.next prev cur"],"choices":["1. nxt=cur.next  2. cur.next=prev  3. prev=cur  4. cur=nxt","1. cur.next=prev  2. prev=cur  3. cur=cur.next (no save)","1. prev=cur  2. cur.next=prev  3. cur=cur.next","1. cur=cur.next  2. cur.next=prev  3. prev=cur"],"tags":["linked-list","reversal","pointer-order"],"timeLimitSec":15,"masteryWeight":1.0,"fullCode":"def reverseList(head):\n    prev=None; cur=head\n    while cur:\n        nxt=cur.next    # SAVE\n        cur.next=prev   # REVERSE\n        prev=cur        # advance prev\n        cur=nxt         # advance cur\n    return prev","fullExplanation":"Save cur.next FIRST before overwriting. Common mistake: overwriting cur.next before saving → lose rest of list. End: prev=new head.","links":["https://leetcode.com/problems/reverse-linked-list/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-trie","problemId":"","topic":"Tries","topicId":"tries","subtopic":"Prefix Matching","subtopicId":"prefix-matching","difficulty":"medium","title":"Trie — when vs hashset","questionType":"multiple_choice","prompt":"Need to check if words START WITH a prefix. Trie vs hashset?","answer":"Trie: O(L) prefix natively; hashset: O(N*L) for prefix scan","acceptedAnswers":["trie O(L) prefix","hashset no prefix support"],"choices":["Trie: O(L) prefix natively; hashset: O(N*L) for prefix scan","Trie uses less memory","Trie is faster for exact lookup","Trie allows O(1) deletion"],"tags":["trie","prefix","recognition"],"timeLimitSec":20,"masteryWeight":1.1,"fullCode":"class TrieNode:\n    def __init__(self): self.ch={}; self.end=False\nclass Trie:\n    def __init__(self): self.root=TrieNode()\n    def insert(self,w):\n        n=self.root\n        for c in w:\n            if c not in n.ch: n.ch[c]=TrieNode()\n            n=n.ch[c]\n        n.end=True\n    def startsWith(self,p):\n        n=self.root\n        for c in p:\n            if c not in n.ch: return False\n            n=n.ch[c]\n        return True","fullExplanation":"Trie: 'prefix', 'starts with', 'autocomplete', 'word search with wildcards'. O(L) insert/search/prefix. Hashset: O(L) exact, O(N*L) prefix.","links":["https://leetcode.com/problems/implement-trie-prefix-tree/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-seg","problemId":"","topic":"Segment Tree","topicId":"segment-tree","subtopic":"Range Query","subtopicId":"range-query","difficulty":"hard","title":"Segment Tree — when to use","questionType":"multiple_choice","prompt":"Range sum QUERIES + point UPDATES, many of each. Best structure?","answer":"Segment Tree — O(log n) both; prefix sum is O(1) query but O(n) update","acceptedAnswers":["segment tree","O(log n) both"],"choices":["Segment Tree — O(log n) both; prefix sum is O(1) query but O(n) update","Prefix sum — O(1) query better overall","Fenwick only — segment tree too complex","HashMap — O(1) for both"],"tags":["segment-tree","range-query","vs-prefix-sum"],"timeLimitSec":20,"masteryWeight":1.2,"fullCode":"class SegTree:\n    def __init__(self,n,a):\n        self.n=n; self.t=[0]*(2*n)\n        for i in range(n): self.t[n+i]=a[i]\n        for i in range(n-1,0,-1): self.t[i]=self.t[2*i]+self.t[2*i+1]\n    def update(self,i,v):\n        i+=self.n; self.t[i]=v\n        while i>1: i//=2; self.t[i]=self.t[2*i]+self.t[2*i+1]\n    def query(self,l,r):\n        res=0; l+=self.n; r+=self.n\n        while l<r:\n            if l&1: res+=self.t[l]; l+=1\n            if r&1: r-=1; res+=self.t[r]\n            l//=2; r//=2\n        return res","fullExplanation":"Range query+point update → Segment Tree or Fenwick, both O(log n). Prefix sum: O(1) query, O(n) update. Use Seg Tree when you need range min/max (Fenwick doesn't support that).","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-fc-bfs","problemId":"","topic":"Graphs","topicId":"graphs","subtopic":"BFS","subtopicId":"bfs","difficulty":"easy","title":"BFS data structure","questionType":"flashcard","prompt":"BFS uses ___ (data structure). DFS uses ___.","answer":"BFS: queue/deque (FIFO). DFS: stack/recursion (LIFO).","acceptedAnswers":["queue","BFS queue DFS stack"],"choices":[],"tags":["bfs","dfs","flashcard"],"timeLimitSec":10,"masteryWeight":0.8,"fullCode":"from collections import deque\nqueue=deque([start]); visited={start}\nwhile queue:\n    node=queue.popleft()\n    for nei in graph[node]:\n        if nei not in visited: visited.add(nei); queue.append(nei)","fullExplanation":"BFS=queue(FIFO): all neighbors before going deeper. DFS=stack: go deep first. BFS guarantees shortest path in unweighted.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-fc-heap","problemId":"","topic":"Heap / Priority Queue","topicId":"heap-priority-queue","subtopic":"Python Heap","subtopicId":"python-heap","difficulty":"easy","title":"Python max heap trick","questionType":"flashcard","prompt":"Python heapq is MIN heap only. How to simulate MAX heap?","answer":"Negate values: push -x, pop and negate (-heapq.heappop(heap))","acceptedAnswers":["negate","push -x"],"choices":[],"tags":["heap","python","flashcard"],"timeLimitSec":10,"masteryWeight":0.8,"fullCode":"import heapq\nh=[]\nheapq.heappush(h,-3); heapq.heappush(h,-1)\nprint(-heapq.heappop(h))  # 3","fullExplanation":"Python heapq: min heap. Max heap: push -x, pop and negate. For tuples: (-priority, value).","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-fc-backtrack","problemId":"","topic":"Backtracking","topicId":"backtracking","subtopic":"Template","subtopicId":"template","difficulty":"easy","title":"Backtracking 3 steps","questionType":"flashcard","prompt":"The 3 steps of backtracking: Choose → ___ → ___.","answer":"Choose → Explore → Unchoose (undo the choice)","acceptedAnswers":["explore unchoose","explore / unchoose"],"choices":[],"tags":["backtracking","template","flashcard"],"timeLimitSec":10,"masteryWeight":0.8,"fullCode":"def bt(path,choices):\n    if base_case(path): result.append(path[:]); return\n    for c in choices:\n        path.append(c)         # CHOOSE\n        bt(path,next_choices)  # EXPLORE\n        path.pop()             # UNCHOOSE","fullExplanation":"Always undo choice after recursive call. Reuse the same path list. Recursive call explores all paths starting with this choice.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-fc-visited","problemId":"","topic":"Graphs","topicId":"graphs","subtopic":"BFS","subtopicId":"bfs","difficulty":"easy","title":"BFS — when to mark visited","questionType":"flashcard","prompt":"In BFS, mark node as visited when you ___ it (not when you process it). Why?","answer":"When you ENQUEUE it — prevents duplicate queue entries and exponential work","acceptedAnswers":["enqueue","push","before queue.append"],"choices":[],"tags":["bfs","visited","pitfall","flashcard"],"timeLimitSec":12,"masteryWeight":1.0,"fullCode":"q=deque([start]); vis={start}  # mark at push\nwhile q:\n    node=q.popleft()\n    for nei in neighbors(node):\n        if nei not in vis:\n            vis.add(nei)  # BEFORE push\n            q.append(nei)","fullExplanation":"Mark BEFORE pushing. If you mark at pop, same node pushed multiple times → exponential work in dense graphs.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-fc-memo-tab","problemId":"","topic":"Dynamic Programming","topicId":"dynamic-programming","subtopic":"Memoization","subtopicId":"memoization","difficulty":"easy","title":"Memoization vs Tabulation","questionType":"flashcard","prompt":"Which avoids stack overflow for deep recursion: memoization or tabulation?","answer":"Tabulation (bottom-up) — iterative, no stack overflow risk","acceptedAnswers":["tabulation","bottom-up","iterative"],"choices":[],"tags":["dp","flashcard"],"timeLimitSec":10,"masteryWeight":0.8,"fullCode":"@lru_cache(None)\ndef fib(n):  # memoization — recursion depth risk\n    if n<=1: return n\n    return fib(n-1)+fib(n-2)\n\ndef fib_tab(n):  # tabulation — safe\n    dp=[0]*(n+1); dp[1]=1\n    for i in range(2,n+1): dp[i]=dp[i-1]+dp[i-2]\n    return dp[n]","fullExplanation":"Memoization: @lru_cache, risk at Python limit ~1000. Tabulation: iterative, handles n=10^6+. For interviews: memoization faster to write; tabulation required for deep recursion.","links":[],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-rotting","problemId":"lc-994-rotting","topic":"Graphs","topicId":"graphs","subtopic":"BFS Multi-source","subtopicId":"bfs-multi-source","difficulty":"medium","title":"Rotting Oranges — multi-source BFS","questionType":"multiple_choice","prompt":"Rotting Oranges (LC 994): all rotten oranges spread simultaneously. Why multi-source BFS?","answer":"Init queue with ALL rotten oranges at t=0 — they all spread simultaneously, not sequentially","acceptedAnswers":["multi-source","all rotten at t=0","all rotten oranges"],"choices":["Init queue with ALL rotten oranges at t=0 — they all spread simultaneously, not sequentially","Run separate BFS from each rotten orange, take minimum","DFS from each rotten orange to find farthest fresh","Sort rotten oranges, process left to right"],"tags":["graphs","bfs","multi-source","matrix"],"timeLimitSec":18,"masteryWeight":1.2,"fullCode":"from collections import deque\ndef orangesRotting(grid):\n    m,n=len(grid),len(grid[0]); q=deque(); fresh=0\n    for r in range(m):\n        for c in range(n):\n            if grid[r][c]==2: q.append((r,c,0))\n            elif grid[r][c]==1: fresh+=1\n    mins=0\n    while q:\n        r,c,t=q.popleft()\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n            nr,nc=r+dr,c+dc\n            if 0<=nr<m and 0<=nc<n and grid[nr][nc]==1:\n                grid[nr][nc]=2; fresh-=1; q.append((nr,nc,t+1)); mins=t+1\n    return mins if fresh==0 else -1","fullExplanation":"Multi-source BFS: init ALL rotten oranges at t=0. Each BFS step = 1 minute, all spread simultaneously. If fresh>0 after BFS → return -1.","links":["https://leetcode.com/problems/rotting-oranges/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-dp-burst","problemId":"lc-312-burst-balloons","topic":"Dynamic Programming","topicId":"dynamic-programming","subtopic":"Interval DP","subtopicId":"interval-dp","difficulty":"hard","title":"Burst Balloons — last burst insight","questionType":"multiple_choice","prompt":"Burst Balloons (LC 312): dp[i][j]=max coins bursting (i..j). Think about the ___ balloon burst in the range.","answer":"LAST — when k is last in (i,j), neighbors always i and j → subproblems [i,k] and [k,j] are independent","acceptedAnswers":["last","last balloon","last burst"],"choices":["LAST — when k is last in (i,j), neighbors always i and j → subproblems [i,k] and [k,j] are independent","FIRST — simplifies range","MIDDLE — divide and conquer","MINIMUM — greedy choice"],"tags":["dp","interval-dp","key-insight"],"timeLimitSec":25,"masteryWeight":1.5,"fullCode":"def maxCoins(nums):\n    nums=[1]+nums+[1]; n=len(nums)\n    dp=[[0]*n for _ in range(n)]\n    for l in range(2,n):\n        for i in range(0,n-l):\n            j=i+l\n            for k in range(i+1,j):  # k = LAST burst\n                dp[i][j]=max(dp[i][j],dp[i][k]+nums[i]*nums[k]*nums[j]+dp[k][j])\n    return dp[0][n-1]","fullExplanation":"Think LAST burst. If k is last in (i,j), only neighbors are i and j → coins=nums[i]*nums[k]*nums[j]. Left [i,k] and right [k,j] don't interact → DP works.","links":["https://leetcode.com/problems/burst-balloons/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
    {"id":"hq-gr-islands","problemId":"lc-200-num-islands","topic":"Graphs","topicId":"graphs","subtopic":"Matrix as Graph","subtopicId":"matrix-as-graph","difficulty":"easy","title":"Number of Islands — flood fill","questionType":"multiple_choice","prompt":"Number of Islands (LC 200): how to mark visited '1' cells efficiently without extra space?","answer":"Modify grid in place: set visited '1' to '0' (sink the island) during DFS/BFS","acceptedAnswers":["set to '0'","modify in place","sink"],"choices":["Modify grid in place: set visited '1' to '0' (sink the island) during DFS/BFS","Separate 2D visited boolean array","Set of (row,col) tuples","Mark with '#' to distinguish"],"tags":["graphs","matrix","island"],"timeLimitSec":12,"masteryWeight":1.0,"fullCode":"def numIslands(grid):\n    m,n=len(grid),len(grid[0]); count=0\n    def dfs(r,c):\n        if r<0 or r>=m or c<0 or c>=n or grid[r][c]!='1': return\n        grid[r][c]='0'  # sink\n        dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n    for r in range(m):\n        for c in range(n):\n            if grid[r][c]=='1': count+=1; dfs(r,c)\n    return count","fullExplanation":"Flood fill: find '1', increment count, sink entire connected island by setting to '0'. O(mn). In-place saves space. If grid must remain unchanged: use visited set.","links":["https://leetcode.com/problems/number-of-islands/"],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True},
]

WRONG_POOL = {
    "binary-search": ["Linear scan left to right","Sort first then scan","Use hashmap O(1) lookup","BFS level traversal"],
    "graphs": ["Greedy by edge weight","Prefix sum of matrix","Binary search on node index","Sort nodes by degree"],
    "dynamic-programming": ["Greedy local max","Sort then two pointers","Fixed-size sliding window","Binary search on answer"],
    "sliding-window": ["Sort then binary search","Nested O(n²) check","Prefix sum + hashmap","DFS on array"],
    "stack-monotonic-stack": ["Binary search for boundary","Prefix max/min arrays","Sort then greedy","Two pointers from ends"],
    "backtracking": ["DP with memoization","BFS layer enumeration","Greedy at each step","Union Find connectivity"],
    "heap-priority-queue": ["Sort all then index","Binary search sorted list","DFS for extremes","Prefix sum for ranges"],
    "trees": ["Two-pointer on array","Binary search on values","Sliding window on path","Union Find connectivity"],
    "prefix-sum": ["Sort and scan","Binary search on values","Sliding window","DFS traversal"],
    "default": ["Nested O(n²) loop","Sort and greedy select","Binary search on answer","Hash every element"],
}

def get_wrong(tid, correct):
    pool = WRONG_POOL.get(tid, WRONG_POOL["default"])
    return [c for c in pool if c.lower().strip() != correct.lower().strip()][:3]

def auto_questions(problems):
    random.seed(42); qs = []; seen = set()
    for p in problems:
        if not p["title"] or len(p["title"]) < 3: continue
        tid = p["topicId"]; title = p["title"]
        summary = p["summary"] or title
        if p["recognition_cues"]:
            cue = p["recognition_cues"][0]
            wrong = get_wrong(tid, cue)
            if len(wrong) >= 3:
                choices = [cue] + wrong; random.shuffle(choices)
                qid = f"q-recog-{slugify(title)}-{uuid.uuid4().hex[:5]}"
                if qid not in seen:
                    seen.add(qid)
                    qs.append({"id":qid,"problemId":p["id"],"topic":p["topic"],"subtopic":p["subtopic"],"topicId":tid,"subtopicId":p["subtopicId"],"difficulty":p["difficulty"],"title":f"{title} — Pattern","questionType":"multiple_choice","prompt":f"{title}: {summary[:200]} What is the primary recognition cue?","answer":cue,"acceptedAnswers":[cue],"choices":choices,"tags":[tid,"recognition"],"timeLimitSec":15,"masteryWeight":1.0,"fullCode":p["code"][:800] if p["code"] else "","fullExplanation":f"Recognition for {title}: {cue}. Topic: {p['topic']}.","links":p["links"][:1],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True})
        for ins in p["insights"][:2]:
            if len(ins) < 20 or len(ins) > 220: continue
            qid = f"q-fc-{slugify(title)}-{uuid.uuid4().hex[:5]}"
            if qid not in seen:
                seen.add(qid)
                qs.append({"id":qid,"problemId":p["id"],"topic":p["topic"],"subtopic":p["subtopic"],"topicId":tid,"subtopicId":p["subtopicId"],"difficulty":p["difficulty"],"title":f"{title} — Insight","questionType":"flashcard","prompt":f"Key insight for {title}:","answer":ins,"acceptedAnswers":[ins],"choices":[],"tags":[tid,"flashcard"],"timeLimitSec":10,"masteryWeight":0.8,"fullCode":p["code"][:600] if p["code"] else "","fullExplanation":ins,"links":p["links"][:1],"revealFullCodeAfterAnswer":True,"revealFullExplanationAfterAnswer":True})
    return qs

def build_bundle():
    print("Parsing notebooks...")
    topics, problems = parse_notebooks(NOTEBOOKS)
    print(f"  → {len(topics)} topics, {len(problems)} problems")
    auto_qs = auto_questions(problems)
    print(f"  → {len(auto_qs)} auto-generated questions")
    all_qs = HANDCRAFTED + auto_qs
    seen = set(); unique = []
    for q in all_qs:
        if q["id"] not in seen:
            seen.add(q["id"])
            q.setdefault("choices",[])
            q.setdefault("acceptedAnswers",[q.get("answer","")])
            q.setdefault("links",[])
            q.setdefault("tags",[])
            q.setdefault("timeLimitSec",20)
            q.setdefault("masteryWeight",1.0)
            q.setdefault("fullCode","")
            q.setdefault("fullExplanation","")
            q.setdefault("revealFullCodeAfterAnswer",True)
            q.setdefault("revealFullExplanationAfterAnswer",True)
            if not q.get("topicId") and q.get("topic"): q["topicId"]=slugify(q["topic"])
            if not q.get("subtopicId") and q.get("subtopic"): q["subtopicId"]=slugify(q["subtopic"])
            unique.append(q)
    topic_titles = {t["title"] for t in topics}
    for q in HANDCRAFTED:
        if q["topic"] not in topic_titles:
            topics.append({"id":q["topicId"],"title":q["topic"],"subtopics":[q["subtopic"]]})
            topic_titles.add(q["topic"])
        else:
            for t in topics:
                if t["title"]==q["topic"] and q["subtopic"] not in t["subtopics"]:
                    t["subtopics"].append(q["subtopic"])
    topics.sort(key=lambda x:x["title"])
    return {"meta":{"sourceNotebooks":[p.name for p in NOTEBOOKS],"topicCount":len(topics),"problemCount":len(problems),"questionCount":len(unique)},"topics":topics,"problems":problems,"questions":unique}

def main():
    bundle = build_bundle()
    for path in [OUTPUT_PATH, PUBLIC_OUTPUT_PATH]:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_text(json.dumps(bundle, indent=2, ensure_ascii=False))
        print(f"Written → {path}")
    m = bundle["meta"]; hc = len(HANDCRAFTED)
    print(f"\n✓ {m['topicCount']} topics · {m['problemCount']} problems · {m['questionCount']} questions")
    print(f"  {hc} expert handcrafted + {m['questionCount']-hc} auto-generated")

if __name__ == "__main__":
    main()
